const projects = [
  {
    id: 1,
    title: "Genesis Web",
    description: "Сайт финансового сервиса.",
    technologies: "React, TypeScript",
    src: "/images/projectsImages/genesis_preview.png",
    demo: "https://genesis-private.com/",
    modalImages: [
      "/images/projectsImages/genesis_preview.png",
      "/images/projectsImages/genesis-1.png",
      "/images/projectsImages/genesis-2.png",
      "/images/projectsImages/genesis-3.png",
      "/images/projectsImages/genesis-4.png",
      "/images/projectsImages/genesis-5.png",
      "/images/projectsImages/genesis-6.png",
    ],
  },
  {
    id: 2,
    title: "FinAcademia",
    description: "Телеграм-бот для обучения/сервисных функций.",
    technologies: "Telegram Bot API, Node.js / Python",
    src: "/images/projectsImages/finacademia_preview.png",
    demo: "https://t.me/FinAcademiaBot",
    modalImages: [
      "/images/projectsImages/finacademia-1.png",
      "/images/projectsImages/finacademia-2.png",
    ],
  },
  {
    id: 3,
    title: "CarTrader Pro",
    description: "Телеграм-бот для торговли авто/объявлений.",
    technologies: "Telegram Bot API, Node.js / Python",
    src: "/images/projectsImages/cartrader_preview.png",
    demo: "https://t.me/CarTraderProBot",
    modalImages: [
      "/images/projectsImages/cartrader-1.png",
      "/images/projectsImages/cartrader-2.png",
      "/images/projectsImages/cartrader-3.png",
      "/images/projectsImages/cartrader-4.png",
      "/images/projectsImages/cartrader-5.png",
      "/images/projectsImages/cartrader-6.png",
      "/images/projectsImages/cartrader-7.png",
      "/images/projectsImages/cartrader-8.png",
      "/images/projectsImages/cartrader-9.png",
      "/images/projectsImages/cartrader-10.png",
      "/images/projectsImages/cartrader-11.png",
      "/images/projectsImages/cartrader-12.png",
      "/images/projectsImages/cartrader-13.png",
      "/images/projectsImages/cartrader-14.png",
      "/images/projectsImages/cartrader-15.png",
    ],
  },
  {
    id: 4,
    title: "Clicker",
    description: "Игровой кликер в Telegram.",
    technologies: "Telegram Mini Apps",
    src: "/images/projectsImages/clicker_preview.png",
    demo: "https://t.me/bytecoin__bot",
    modalImages: [
      "/images/projectsImages/clicker-1.png",
      "/images/projectsImages/clicker-2.png",
      "/images/projectsImages/clicker-3.png",
      "/images/projectsImages/clicker-4.png",
      "/images/projectsImages/clicker-5.png",
      "/images/projectsImages/clicker-6.png",
      "/images/projectsImages/clicker-7.png",
    ],
  },
  {
    id: 5,
    title: "SwapKitty",
    description: "Телеграм-бот для обменов/транзакций.",
    technologies: "Telegram Bot API",
    src: "/images/projectsImages/swapkitty_preview.png",
    demo: "https://t.me/SwapKitty_bot",
    modalImages: [
      "/images/projectsImages/swapkitty-1.png",
      "/images/projectsImages/swapkitty-2.png",
    ],
  },
  {
    id: 6,
    title: "Calculator",
    description: "Телеграм-бот для быстрых расчётов.",
    technologies: "Telegram Bot API",
    src: "/images/projectsImages/calculator_preview.png",
    demo: "https://t.me/CalcFastBot",
    modalImages: [
      "/images/projectsImages/calculator-1.png",
      "/images/projectsImages/calculator-2.png",
    ],
  },
];

export default projects;
